apiVersion: v1
kind: Service
metadata:
  name: weave-flux-cicd-eks
  namespace: weave-flux-cicd-eks
  labels:
    app: weave-flux-cicd-eks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: weave-flux-cicd-eks
